spring:
  #Habilita lançamento de exceptions NoHandlerFoundException
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: true
  datasource:
    url: ${DATASOURCE_URL}
  profiles:
    active: ${PROD_PROFILE:dev}

#Formata saída colorida no console
  output:
    ansi:
      enabled: ALWAYS

  #Configuração do Jackson para habilitar lançamento de exceptions conforme atributos abaixo
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true