spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/tcc-parking-iot?useTimezone=true&serverTimezone=UTC
    username: ${username}
    password: ${password}
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
      format_sql: true